# Generated by Django 4.0.1 on 2022-01-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
