# Generated by Django 4.0.1 on 2022-01-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_gsuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gsuser',
            name='is_admin',
        ),
    ]
